services:
  back-end:
    build: ./app/
    container_name: back-end
    image: chemuske013/back-end:latest
    ports:
      - 8000:8000
    environment:
      - name=value

  front-end:
    build: ./front
    container_name: front-end
    image: chemuske013/front-end
    environment:
      - BACKEND_URL="http://back-end:5000/"
    ports:
      - 80:80
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass